name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Typecheck
        run: deno check mod.ts

      - name: Lint
        run: deno lint

      - name: Check formatting
        run: deno check mod.ts
